apiVersion: v1
kind: PersistentVolume
metadata:
  name: gpu-storage
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/data/NFS"
    server: 10.0.5.24
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: gpu
  labels:
    component: influxdb
    app: influxdb
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 8086
    targetPort: 8086
    name: server
  selector:
    component: influxdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: gpu
  name: influxdb
  labels:
    component: influxdb
    app: influxdb
spec:
  serviceName: influxdb
  selector:
    matchLabels:
      component: influxdb
  replicas: 1
  template:
    metadata:
      name: influxdb
      labels:
        component: influxdb
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.6.4
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2G
          requests:
            memory: 1G
        env:
          - name: INFLUXDB_IFQL_ENABLED
            value: "true"
          - name: INFLUXDB_LOGGING_LEVEL
            value: "error"
          - name: INFLUXDB_HTTP_LOG_ENABLED
            value: "false"
        volumeMounts:
          - name: gpu-storage
            mountPath: /data/mountNFS
        ports:
          - containerPort: 8086
            name: server
          - containerPort: 8082
            name: ifql
  volumeClaimTemplates:
  - metadata:
       name: gpu-storage
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 2Gi


